[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_SPACE_ID = "n6mfbxszk579"
  CONTENTFUL_ACCESS_TOKEN = "2-6zZegHLri5YwAp-RjZmBPJtBzWJiBBSOfBn7Y6e4k"
  CONTENTFUL_PREVIEW_ACCESS_TOKEN = "t3M3VRXmnef0GjRusEjWj2wWWEiDQvK1mQSecMSvJJM"
