[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_SPACE_ID = "o2xpsub0dh03"
  CONTENTFUL_ACCESS_TOKEN = "CFPAT-eGVamUSKUeBqGTvdkXqyPUEoFLqNyqhqrRCFTjxc9oE"
  CONTENTFUL_PREVIEW_ACCESS_TOKEN = "tcMTlsYxEn5Mgx54fdK8CeExVSjtkfCluKJp0LLKODY"
